/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#a63b01',
        'on-primary': '#ffffff',
        'on-tertiary-fixed-variant': '#7f2b00',
        'tertiary-fixed': '#ffdbce',
        'outline-variant': '#c3c6d6',
        'on-secondary-fixed': '#141d23',
        'inverse-surface': '#2e3038',
        'primary-fixed-dim': '#b0c6ff',
        'on-background': '#191b22',
        'on-secondary': '#ffffff',
        'surface': '#faf8ff',
        'error': '#ba1a1a',
        'primary-container': '#0a58ca',
        'surface-variant': '#e1e2ec',
        'on-secondary-container': '#5b646b',
        'primary-fixed': '#d9e2ff',
        'surface-dim': '#d9d9e3',
        'surface-container-highest': '#e1e2ec',
        'on-primary-fixed-variant': '#00419d',
        'primary': '#00429d',
        'error-container': '#ffdad6',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffcebc',
        'on-surface-variant': '#424653',
        'on-primary-fixed': '#001945',
        'background': '#faf8ff',
        'surface-container-high': '#e7e7f1',
        'tertiary-fixed-dim': '#ffb599',
        'secondary-fixed': '#dbe4ed',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#370e00',
        'surface-container-low': '#f2f3fd',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#ededf7',
        'on-surface': '#191b22',
        'surface-tint': '#0958ca',
        'secondary-fixed-dim': '#bfc8d0',
        'surface-bright': '#faf8ff',
        'tertiary': '#7f2b00',
        'on-primary-container': '#ccd8ff',
        'secondary-container': '#d8e1ea',
        'inverse-on-surface': '#f0f0fa',
        'on-secondary-fixed-variant': '#3f484f',
        'inverse-primary': '#b0c6ff',
        'on-error-container': '#93000a',
        'outline': '#737785',
        'secondary': '#575f67',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        xl: '32px',
        md: '16px',
        'margin-desktop': '40px',
        xs: '4px',
        'margin-mobile': '16px',
        lg: '24px',
        sm: '8px',
        unit: '4px',
        'max-width': '1440px',
      },
      fontFamily: {
        'label-md': ['Inter'],
        'headline-lg': ['Inter'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        'headline-md': ['Inter'],
        'code-md': ['JetBrains Mono'],
        'display-lg': ['Inter'],
        'title-lg': ['Inter'],
      },
      fontSize: {
        'label-md': [
          '12px',
          {
            lineHeight: '16px',
            letterSpacing: '0.05em',
            fontWeight: '500',
          },
        ],
        'headline-lg': [
          '32px',
          {
            lineHeight: '40px',
            letterSpacing: '-0.01em',
            fontWeight: '600',
          },
        ],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'code-md': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'display-lg': [
          '48px',
          {
            lineHeight: '56px',
            letterSpacing: '-0.02em',
            fontWeight: '700',
          },
        ],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};