export enum Role {
  ADMIN = 'ADMIN',
  ORDONNANCEUR_ELECTRICITE = 'ORDONNANCEUR_ELECTRICITE',
  ORDONNANCEUR_EAU_ASSAINISSEMENT = 'ORDONNANCEUR_EAU_ASSAINISSEMENT',
  CHEF_EQUIPE = 'CHEF_EQUIPE',
  TECHNICIEN = 'TECHNICIEN',
  CLIENT = 'CLIENT'
}