spring.application.name=pgi
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/srmfm_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.web=TRACE
logging.level.com.pgi.pgic=DEBUG
jwt.secret=mySecretKeyForJWT2026SRMFMProjectVeryLongAndSecureKey
jwt.expiration=86400000
spring.flyway.baseline-on-migrate=true
server.port=8082
file.upload-dir=./uploads
logging.level.com.pgi.pgic.controller.OrdonnanceurController=TRACE
logging.level.com.pgi.pgic.service.OrdonnanceurService=TRACE
spring.jpa.properties.hibernate.loader.disable_multi_bag_fetch=true